import {
  Boxes,
  Building2,
  CircleDollarSign,
  ClipboardList,
  HardDrive,
  Inbox,
  MessageCircle,
  Settings,
  UserCog,
  Users,
  Wrench,
  Tags,
  Package,
} from 'lucide-react'
import {
  USER_ROLES,
  PRIORITES,
  PAIEMENT_MODES,
} from './domainConstants'

export const ADMIN_ENTITIES = [
  {
    key: 'users',
    label: 'Users',
    icon: Users,
    serviceKey: 'users',
    columns: [
      'username',
      'email',
      'first_name',
      'last_name',
      'role',
      'telephone',
      'department',
    ],
    fields: [
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'password', label: 'Password', type: 'password', requiredOnCreate: true },
      {
        key: 'role',
        label: 'Role',
        type: 'select',
        required: true,
        options: USER_ROLES,
      },
      { key: 'first_name', label: 'First Name', type: 'text' },
      { key: 'last_name', label: 'Last Name', type: 'text' },
      { key: 'telephone', label: 'Telephone', type: 'text' },
      { key: 'image', label: 'Photo', type: 'image' },
      {
        key: 'department_id',
        label: 'Department',
        type: 'lookup',
        lookup: { serviceKey: 'departments', valueKey: 'id', labelKey: 'nom_dept' },
      },
    ],
  },
  {
    key: 'departments',
    label: 'Departments',
    icon: Building2,
    serviceKey: 'departments',
    maxRecords: 5,
    columns: ['id', 'nom_dept', 'description', 'date_creation'],
    fields: [
      { key: 'nom_dept', label: 'Department Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'date_creation', label: 'Creation Date', type: 'date', readOnly: true },
    ],
  },
  {
    key: 'clients',
    label: 'Clients',
    icon: UserCog,
    serviceKey: 'clients',
    columns: ['id', 'nom_complet', 'email', 'telephone', 'adresse', 'date_creation'],
    fields: [
      { key: 'nom_complet', label: 'Full Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'telephone', label: 'Telephone', type: 'text', required: true },
      { key: 'adresse', label: 'Address', type: 'textarea' },
      { key: 'date_creation', label: 'Creation Date', type: 'date', readOnly: true },
    ],
  },
  {
    key: 'categories-materiel',
    label: 'Catégories Matériel',
    icon: Tags,
    serviceKey: 'categories-materiel',
    columns: ['id', 'nom', 'description', 'is_active', 'date_creation'],
    fields: [
      { key: 'nom', label: 'Nom', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'is_active', label: 'Actif', type: 'boolean' },
      { key: 'date_creation', label: 'Date de Création', type: 'date', readOnly: true },
    ],
  },
  {
    key: 'materiels',
    label: 'Materiels',
    icon: HardDrive,
    serviceKey: 'materiels',
    columns: [
      'id',
      'client',
      'type',
      'marque',
      'modele',
      'numero_serie',
      'etat',
      'date_reception',
    ],
    fields: [
      {
        key: 'client',
        label: 'Client',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'clients', valueKey: 'id', labelKey: 'nom_complet' },
      },
      { key: 'type', label: 'Type', type: 'text', required: true },
      { key: 'marque', label: 'Brand', type: 'text', required: true },
      { key: 'modele', label: 'Model', type: 'text', required: true },
      { key: 'numero_serie', label: 'Serial Number', type: 'text', required: true },
      { key: 'etat', label: 'Status', type: 'text' },
      { key: 'date_reception', label: 'Reception Date', type: 'date' },
    ],
  },
  {
    key: 'demande-maintenances',
    label: 'Demande Maintenances',
    icon: ClipboardList,
    serviceKey: 'demande-maintenances',
    columns: ['id', 'materiel', 'receptioniste', 'manager', 'priorite', 'statut', 'date_creation'],
    fields: [
      {
        key: 'materiel',
        label: 'Materiel',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'materiels', valueKey: 'id', labelKey: 'numero_serie' },
      },
      {
        key: 'receptioniste',
        label: 'Receptioniste',
        type: 'lookup',
        lookup: { serviceKey: 'users', valueKey: 'id', labelKey: 'username' },
      },
      {
        key: 'manager',
        label: 'Manager',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'users', valueKey: 'id', labelKey: 'username', filter: (user) => user.role === 'manager' },
      },
      {
        key: 'priorite',
        label: 'Priority',
        type: 'select',
        options: PRIORITES,
        required: true,
      },
      { key: 'date_creation', label: 'Creation Date', type: 'date', readOnly: true },
    ],
  },
  {
    key: 'interventions',
    label: 'Interventions',
    icon: Wrench,
    serviceKey: 'interventions',
    columns: [
      'id',
      'demande',
      'technicien',
      'diagnostic',
      'solution_proposee',
      'date_debut',
      'date_fin',
      'statut',
    ],
    fields: [
      {
        key: 'demande',
        label: 'Demande',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'demande-maintenances', valueKey: 'id', labelKey: 'id' },
      },
      {
        key: 'technicien',
        label: 'Technicien',
        type: 'lookup',
        lookup: {
          serviceKey: 'users',
          valueKey: 'id',
          labelKey: 'username',
          filter: (user, context) => {
            if (context?.currentUserId && context?.users?.length && context?.auth?.role === 'manager') {
               const managerData = context.users.find(u => Number(u.id) === context.currentUserId)
               const deptId = managerData?.department?.id
               return user.role === 'technicien' && (!deptId || user.department?.id === deptId)
            }
            return user.role === 'technicien'
          }
        },
      },
      { key: 'diagnostic', label: 'Diagnostic', type: 'textarea' },
      { key: 'solution_proposee', label: 'Proposed Solution', type: 'textarea' },
      { key: 'date_debut', label: 'Start Date', type: 'date' },
      { key: 'date_fin', label: 'End Date', type: 'date' },
    ],
  },
  {
    key: 'achat-piece',
    label: 'Achat Pièce',
    icon: Package,
    serviceKey: 'fournisseurs',
    columns: ['id', 'bundle'],
    fields: [],
  },
  {
    key: 'fiche-reparations',
    label: 'Fiche Reparations',
    icon: Settings,
    serviceKey: 'fiche-reparations',
    columns: [
      'id',
      'intervention',
      'description_panne',
      'solution',
      'cout_main_oeuvre',
      'frais_societe',
      'prix_supplementaire',
      'confirmation',
      'valide_manager',
    ],
    fields: [
      {
        key: 'intervention',
        label: 'Intervention',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'interventions', valueKey: 'id', labelKey: 'id' },
      },
      { key: 'description_panne', label: 'Issue Description', type: 'textarea' },
      { key: 'solution', label: 'Solution', type: 'textarea' },
      { key: 'cout_main_oeuvre', label: 'Labor Cost', type: 'number' },
      { key: 'frais_societe', label: 'Society Fees', type: 'number' },
      { key: 'prix_supplementaire', label: 'Additional Price', type: 'number' },
      { key: 'confirmation', label: 'Confirmed', type: 'boolean' },
      { key: 'valide_manager', label: 'Validated By Manager', type: 'boolean' },
    ],
  },
  {
    key: 'pieces',
    label: 'Stock Pièce',
    icon: Boxes,
    serviceKey: 'pieces',
    columns: ['id', 'nom', 'reference', 'modele', 'categorie', 'quantite_stock', 'seuil_alerte', 'statut_stock', 'prix_unitaire'],
    fields: [
      { key: 'nom', label: 'Name', type: 'text', required: true },
      { key: 'reference', label: 'Reference / SKU', type: 'text' },
      { key: 'modele', label: 'Model', type: 'text' },
      {
        key: 'categorie',
        label: 'Category',
        type: 'lookup',
        lookup: { serviceKey: 'categories-materiel', valueKey: 'id', labelKey: 'nom' },
      },
      { key: 'quantite_stock', label: 'Stock Quantity', type: 'number', required: true },
      { key: 'seuil_alerte', label: 'Alert Threshold', type: 'number' },
      { key: 'prix_unitaire', label: 'Unit Price', type: 'number', required: true },
    ],
  },
  {
    key: 'demande-pieces',
    label: 'Pièce Demandée',
    icon: Inbox,
    serviceKey: 'demande-pieces',
    columns: ['id', 'fiche', 'piece', 'quantite', 'statut', 'date_demande'],
    fields: [
      {
        key: 'fiche',
        label: 'Fiche',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'fiche-reparations', valueKey: 'id', labelKey: 'id' },
      },
      {
        key: 'piece',
        label: 'Piece',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'pieces', valueKey: 'id', labelKey: 'nom' },
      },
      { key: 'quantite', label: 'Quantity', type: 'number', required: true },
      { key: 'date_demande', label: 'Demand Date', type: 'date', readOnly: true },
    ],
  },
  {
    key: 'factures',
    label: 'Factures',
    icon: CircleDollarSign,
    serviceKey: 'factures',
    columns: ['id', 'intervention', 'client', 'montant_total', 'date_facture', 'est_payee'],
    fields: [
      {
        key: 'intervention',
        label: 'Intervention',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'interventions', valueKey: 'id', labelKey: 'id' },
      },
      {
        key: 'client',
        label: 'Client',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'clients', valueKey: 'id', labelKey: 'nom_complet' },
      },
      { key: 'montant_total', label: 'Total Amount', type: 'number', required: true },
      { key: 'date_facture', label: 'Invoice Date', type: 'date' },
    ],
  },
  {
    key: 'paiements',
    label: 'Paiements',
    icon: CircleDollarSign,
    serviceKey: 'paiements',
    columns: ['id', 'facture', 'montant', 'mode_paiement', 'date_paiement'],
    fields: [
      {
        key: 'facture',
        label: 'Facture',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'factures', valueKey: 'id', labelKey: 'id' },
      },
      { key: 'montant', label: 'Amount', type: 'number', required: true },
      {
        key: 'mode_paiement',
        label: 'Payment Mode',
        type: 'select',
        required: true,
        options: PAIEMENT_MODES,
      },
      { key: 'date_paiement', label: 'Payment Date', type: 'date' },
    ],
  },
  {
    key: 'messages',
    label: 'Messages',
    icon: MessageCircle,
    serviceKey: 'messages',
    columns: ['id', 'objet', 'contenu', 'date_envoi', 'expediteur', 'destinataire'],
    fields: [
      { key: 'objet', label: 'Objet', type: 'text' },
      { key: 'contenu', label: 'Contenu', type: 'textarea', required: true },
      {
        key: 'destinataire',
        label: 'Destinataire',
        type: 'lookup',
        required: true,
        lookup: { serviceKey: 'users', valueKey: 'id', labelKey: 'username' },
      },
      { key: 'date_envoi', label: 'Date envoi', type: 'date', readOnly: true },
    ],
  },
]

export const ADMIN_DASHBOARD_ENDPOINTS = [
  { key: 'users', serviceKey: 'users', label: 'Users', icon: Users },
  { key: 'departments', serviceKey: 'departments', label: 'Departments', icon: Building2 },
  { key: 'clients', serviceKey: 'clients', label: 'Clients', icon: UserCog },
  {
    key: 'demande-maintenances',
    serviceKey: 'demande-maintenances',
    label: 'Maintenance Requests',
    icon: ClipboardList,
  },
  { key: 'interventions', serviceKey: 'interventions', label: 'Interventions', icon: Wrench },
  { key: 'achat-piece', serviceKey: 'fournisseurs', label: 'Achat Pièce', icon: Package },
  { key: 'pieces', serviceKey: 'pieces', label: 'Stock Pièce', icon: Boxes },
  { key: 'demande-pieces', serviceKey: 'demande-pieces', label: 'Pièce Demandée', icon: ClipboardList },
  { key: 'factures', serviceKey: 'factures', label: 'Factures', icon: CircleDollarSign },
  { key: 'messages', serviceKey: 'messages', label: 'Messages', icon: MessageCircle },
]

export const adminEntityPath = (entityKey) => `/admin/entities/${entityKey}`

export function getAdminEntityConfig(entityKey) {
  return ADMIN_ENTITIES.find((entity) => entity.key === entityKey) ?? null
}
